# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('line', models.CharField(choices=[('1', '1호선'), ('2', '2호선'), ('3', '3호선')], max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('time_table', models.TextField()),
            ],
        ),
    ]
