# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('file', models.FileField(upload_to=main.models.get_music_upload_path)),
            ],
        ),
    ]
