# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='재생 순서'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
