# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160806_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='order',
        ),
        migrations.AddField(
            model_name='music',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='재생 우선순위'),
        ),
    ]
