# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160806_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date_time',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 5, 57, 57, 491419, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
