# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161017_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to=main.models.get_photo_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
